<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RiveTT.Core\RiveTT.Core.csproj" />
    <ProjectReference Include="..\RiveTT.Plugin\RiveTT.Plugin.csproj" />
    <ProjectReference Include="..\RiveTT.Server\RiveTT.Server.csproj" />
    <ProjectReference Include="..\RiveTT.Tools\RiveTT.Tools.csproj" />
  </ItemGroup>
</Project>
